/**
 * 所有预置的模型提供商配置
 * API密钥从环境变量读取，运行时由ConfigManager注入
 *
 * 模型列表: 包含最新版本(2026) + 旧版本(标记为Legacy)，确保用户可以看到全版本
 */
export const PROVIDER_PRESETS = [
    // ========== DeepSeek ==========
    {
        id: 'deepseek',
        name: 'DeepSeek',
        baseURL: 'https://api.deepseek.com/v1',
        apiKey: '',
        apiKeyEnv: 'DEEPSEEK_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'deepseek-v4',
        headers: {
            'User-Agent': 'EasyAgent/1.0',
        },
        models: [
            // V4 系列 (2026 最新)
            {
                id: 'deepseek-v4',
                name: 'DeepSeek V4',
                maxContextTokens: 131072,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 2, output: 8 },
            },
            {
                id: 'deepseek-v4-flash',
                name: 'DeepSeek V4 Flash',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 0.5, output: 2 },
            },
            // V3 系列
            {
                id: 'deepseek-chat',
                name: 'DeepSeek V3',
                maxContextTokens: 65536,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 1, output: 2 },
            },
            // R1 推理系列
            {
                id: 'deepseek-r1',
                name: 'DeepSeek R1',
                maxContextTokens: 65536,
                maxOutputTokens: 32768,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 4, output: 16 },
            },
        ],
    },
    // ========== 智谱GLM ==========
    {
        id: 'zhipu',
        name: '智谱GLM',
        baseURL: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: '',
        apiKeyEnv: 'ZHIPU_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'glm-5',
        models: [
            // GLM-5 系列 (2026 最新)
            {
                id: 'glm-5',
                name: 'GLM-5',
                maxContextTokens: 200000,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 3, output: 12 },
            },
            {
                id: 'glm-5-flash',
                name: 'GLM-5 Flash',
                maxContextTokens: 200000,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 0.5, output: 2 },
            },
            // GLM-4 系列
            {
                id: 'glm-4-plus',
                name: 'GLM-4 Plus',
                maxContextTokens: 128000,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 50, output: 50 },
            },
            {
                id: 'glm-4-flash',
                name: 'GLM-4 Flash',
                maxContextTokens: 128000,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 0.1, output: 0.1 },
            },
            {
                id: 'glm-4-air',
                name: 'GLM-4 Air',
                maxContextTokens: 128000,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 1, output: 1 },
            },
        ],
    },
    // ========== 通义千问 ==========
    {
        id: 'qwen',
        name: '通义千问',
        baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        apiKey: '',
        apiKeyEnv: 'DASHSCOPE_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'qwen3-max',
        models: [
            // Qwen3 系列 (2026 最新)
            {
                id: 'qwen3-max',
                name: 'Qwen3 Max',
                maxContextTokens: 131072,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 3, output: 12 },
            },
            {
                id: 'qwen3-plus',
                name: 'Qwen3 Plus',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 1.5, output: 6 },
            },
            {
                id: 'qwen3-turbo',
                name: 'Qwen3 Turbo',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.5, output: 2 },
            },
            {
                id: 'qwen3-coder-plus',
                name: 'Qwen3 Coder Plus',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 2, output: 8 },
            },
            // Qwen2 系列 (上一代)
            {
                id: 'qwen-max',
                name: 'Qwen Max (Qwen2)',
                maxContextTokens: 32768,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 20, output: 60 },
            },
            {
                id: 'qwen-plus',
                name: 'Qwen Plus (Qwen2)',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 2, output: 6 },
            },
            {
                id: 'qwen-turbo',
                name: 'Qwen Turbo (Qwen2)',
                maxContextTokens: 1000000,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.3, output: 0.6 },
            },
            {
                id: 'qwen-coder-plus',
                name: 'Qwen Coder Plus (Qwen2)',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 3.5, output: 7 },
            },
        ],
    },
    // ========== Kimi (月之暗面) ==========
    {
        id: 'kimi',
        name: 'Kimi (月之暗面)',
        baseURL: 'https://api.moonshot.cn/v1',
        apiKey: '',
        apiKeyEnv: 'MOONSHOT_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'kimi-k2.7-code',
        models: [
            // K2 系列 (2026 最新)
            {
                id: 'kimi-k2.7-code',
                name: 'Kimi K2.7 Code',
                maxContextTokens: 131072,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 10, output: 30 },
            },
            {
                id: 'kimi-k2.6',
                name: 'Kimi K2.6',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 8, output: 24 },
            },
            {
                id: 'kimi-k2.5',
                name: 'Kimi K2.5',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 5, output: 15 },
            },
            // MoonShot V1 系列 (旧版)
            {
                id: 'moonshot-v1-8k',
                name: 'Kimi 8K (V1)',
                maxContextTokens: 8192,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 12, output: 12 },
            },
            {
                id: 'moonshot-v1-32k',
                name: 'Kimi 32K (V1)',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 24, output: 24 },
            },
            {
                id: 'moonshot-v1-128k',
                name: 'Kimi 128K (V1)',
                maxContextTokens: 131072,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 60, output: 60 },
            },
        ],
    },
    // ========== 文心一言 (百度) ==========
    {
        id: 'ernie',
        name: '文心一言',
        baseURL: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat',
        apiKey: '',
        apiKeyEnv: 'ERNIE_API_KEY',
        apiFormat: 'custom',
        defaultModel: 'ernie-4.5-8k',
        models: [
            // ERNIE 4.5 系列 (2026 最新)
            {
                id: 'ernie-4.5-8k',
                name: 'ERNIE 4.5',
                maxContextTokens: 8192,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 4, output: 12 },
            },
            {
                id: 'ernie-speed',
                name: 'ERNIE Speed',
                maxContextTokens: 128000,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.5, output: 2 },
            },
            {
                id: 'ernie-lite',
                name: 'ERNIE Lite',
                maxContextTokens: 128000,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.3, output: 0.6 },
            },
            // ERNIE 4.0 系列 (旧版)
            {
                id: 'ernie-4.0-8k',
                name: 'ERNIE 4.0',
                maxContextTokens: 8192,
                maxOutputTokens: 2048,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 30, output: 90 },
            },
            {
                id: 'ernie-4.0-turbo-8k',
                name: 'ERNIE 4.0 Turbo',
                maxContextTokens: 8192,
                maxOutputTokens: 2048,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 15, output: 45 },
            },
            {
                id: 'ernie-3.5-8k',
                name: 'ERNIE 3.5',
                maxContextTokens: 8192,
                maxOutputTokens: 2048,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 2, output: 8 },
            },
        ],
    },
    // ========== 豆包 (字节跳动) ==========
    {
        id: 'doubao',
        name: '豆包 (字节跳动)',
        baseURL: 'https://ark.cn-beijing.volces.com/api/v3',
        apiKey: '',
        apiKeyEnv: 'DOUBAO_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'doubao-seed-1.6',
        models: [
            // Seed 1.6 系列 (2026 最新)
            {
                id: 'doubao-seed-1.6',
                name: '豆包 Seed 1.6',
                maxContextTokens: 131072,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 1, output: 4 },
            },
            {
                id: 'doubao-pro-1.6',
                name: '豆包 Pro 1.6',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.8, output: 2 },
            },
            {
                id: 'doubao-lite-1.6',
                name: '豆包 Lite 1.6',
                maxContextTokens: 131072,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.3, output: 0.6 },
            },
            // 旧版
            {
                id: 'doubao-pro-32k',
                name: '豆包 Pro 32K (旧版)',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.8, output: 2 },
            },
            {
                id: 'doubao-pro-128k',
                name: '豆包 Pro 128K (旧版)',
                maxContextTokens: 131072,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 5, output: 9 },
            },
            {
                id: 'doubao-lite-32k',
                name: '豆包 Lite 32K (旧版)',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.3, output: 0.6 },
            },
        ],
    },
    // ========== 腾讯混元 ==========
    {
        id: 'hunyuan',
        name: '腾讯混元',
        baseURL: 'https://hunyuan.tencentcloudapi.com',
        apiKey: '',
        apiKeyEnv: 'HUNYUAN_SECRET_ID',
        apiFormat: 'custom',
        defaultModel: 'hunyuan-turbos-vision-latest',
        models: [
            // 混元 TurboS 系列 (2026 最新)
            {
                id: 'hunyuan-turbos-vision-latest',
                name: '混元 TurboS Vision',
                maxContextTokens: 131072,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 3, output: 12 },
            },
            {
                id: 'hunyuan-t1',
                name: '混元 T1 (推理)',
                maxContextTokens: 65536,
                maxOutputTokens: 32768,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 5, output: 20 },
            },
            // 旧版
            {
                id: 'hunyuan-pro',
                name: '混元 Pro',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 3, output: 10 },
            },
            {
                id: 'hunyuan-standard',
                name: '混元 Standard',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.5, output: 2 },
            },
            {
                id: 'hunyuan-lite',
                name: '混元 Lite',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.2, output: 0.8 },
            },
        ],
    },
    // ========== MiniMax ==========
    {
        id: 'minimax',
        name: 'MiniMax',
        baseURL: 'https://api.minimax.chat/v1',
        apiKey: '',
        apiKeyEnv: 'MINIMAX_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'minimax-m3',
        models: [
            // M3 系列 (2026 最新)
            {
                id: 'minimax-m3',
                name: 'MiniMax M3',
                maxContextTokens: 200000,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 2, output: 8 },
            },
            {
                id: 'minimax-m3-flash',
                name: 'MiniMax M3 Flash',
                maxContextTokens: 200000,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0.5, output: 2 },
            },
            // M1 系列
            {
                id: 'minimax-m1',
                name: 'MiniMax M1',
                maxContextTokens: 131072,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 1, output: 4 },
            },
            // ABAB 系列 (旧版)
            {
                id: 'abab6.5s-chat',
                name: 'ABAB 6.5s',
                maxContextTokens: 245760,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 1, output: 1 },
            },
        ],
    },
    // ========== Ollama (本地) ==========
    {
        id: 'ollama',
        name: 'Ollama (本地)',
        baseURL: 'http://localhost:11434/v1',
        apiKey: 'ollama',
        apiKeyEnv: 'OLLAMA_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'qwen2.5:7b',
        models: [
            {
                id: 'qwen3.5:9b',
                name: 'Qwen 3.5 9B',
                maxContextTokens: 32768,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0, output: 0 },
            },
            {
                id: 'qwen3.5:4b',
                name: 'Qwen 3.5 4B',
                maxContextTokens: 32768,
                maxOutputTokens: 8192,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0, output: 0 },
            },
            {
                id: 'qwen2.5:7b',
                name: 'Qwen 2.5 7B',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0, output: 0 },
            },
            {
                id: 'deepseek-r1:8b',
                name: 'DeepSeek R1 8B',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0, output: 0 },
            },
            {
                id: 'glm4:9b',
                name: 'GLM-4 9B',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0, output: 0 },
            },
        ],
    },
    // ========== OpenAI (兼容) ==========
    {
        id: 'openai',
        name: 'OpenAI (兼容接口)',
        baseURL: 'https://api.openai.com/v1',
        apiKey: '',
        apiKeyEnv: 'OPENAI_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'gpt-4o',
        models: [
            {
                id: 'gpt-4o',
                name: 'GPT-4o',
                maxContextTokens: 128000,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 18, output: 54 },
            },
            {
                id: 'gpt-4o-mini',
                name: 'GPT-4o Mini',
                maxContextTokens: 128000,
                maxOutputTokens: 16384,
                supportsTools: true,
                supportsVision: true,
                pricing: { input: 1, output: 4 },
            },
        ],
    },
    // ========== 自定义 ==========
    {
        id: 'custom',
        name: '自定义',
        baseURL: 'http://localhost:8000/v1',
        apiKey: '',
        apiKeyEnv: 'CUSTOM_API_KEY',
        apiFormat: 'openai',
        defaultModel: 'custom-model',
        models: [
            {
                id: 'custom-model',
                name: '自定义模型',
                maxContextTokens: 32768,
                maxOutputTokens: 4096,
                supportsTools: true,
                supportsVision: false,
                pricing: { input: 0, output: 0 },
            },
        ],
    },
];
//# sourceMappingURL=ProviderPresets.js.map