name: CI Test

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '20'
  npm_config_msvs_version: '2022'

jobs:
  job-a:
    name: Job A (base)
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: echo "Job A OK"

  job-b:
    name: Job B (needs A)
    needs: job-a
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: echo "Job B OK"
